#Mysql设置
Mysql:
  Url: "localhost:3306"
  Name: "root"
  Password: "test123"
  Database: "test"
#消息  把不想要的消息设置为""即可!
Message:
  tired: "§f[§a轻功§f] §e你累了休息一下吧~"
  nopoint: "§f[§a轻功§f] §e你没有足够的点数"
  maxlevel: "§f[§a轻功§f] §e你已经达到最高级,无法升级"
  success: "&f[&a轻功&f] &e加点成功,当前等级: &e%0%"
#取消掉落伤害
CancelFallDamage: true
#Lore检测  可以写到物品的Lore里面 例如: &a连跳次数: +2   还没写
Lore:
  Enable: true
  lore: "&a连跳次数:"
#是否开启粒子特效
Particle:
  Enable: true
#音效设置
Sounds:
  #是否开启
  Enable: true
  #音效
  Sound: ENTITY_PLAYER_LEVELUP
  #音量
  Volume: 1
  #音调
  Pitch: 1
#最大等级设置
MaxLevel: 3
#等级设置
Level:
  #等级 （初始等级）
  1:
  #力度
    Multiply: 1.5
  #高度
    Y: 1
  #冷却时间(s)
    Cd: 3
  #跳跃次数
    Jumps: 2
  2:
    #力度
    Multiply: 1.9
    #高度
    Y: 1
    #冷却时间(s)
    Cd: 3
    #跳跃次数
    Jumps: 3
  3:
    #力度
    Multiply: 2.3
    #高度
    Y: 1.5
    #冷却时间(s)
    Cd: 2.5
    #跳跃次数
    Jumps: 3


