name: WsLightKungFu
version: '0.0.3'
main: cn.whitesoul.wslightkungfu.Main
depend:
  - ParticleLib
  - WsLib
commands:
    lightkungfu:
        description: 轻功
        aliases: [lkf]
        permission: lightkungfu.use
        permission-message: "§f[§a轻功§f] §e你没有权限使用此命令"